services:
  hamaralabs-rtl:
    container_name: hamaralabs-rtl
    restart: always
    image: ghcr.io/vmss2009/hamaralabs-rtl:v1
    init: true
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - hamaralabs-network

networks:
  hamaralabs-network:
    external: true
